//This Code Autometically Generated by jeba Rahman. NOTE: Do not try to copy code, learn yourself
#include<bits/stdc++.h>
using namespace std;
int main()
{
int t;
cin >> t;
while(t--){
    int n;
    cin >> n;
    string s;
    cin >> s;
    set<char> se;
    for(int i = 0; i < n; i++){
        s.(s[i]);
    }

    
}
return 0;
}