//This Code Autometically Generated by jeba Rahman. NOTE: Do not try to copy code, learn yourself
#include<bits/stdc++.h>
using namespace std;
int main()
{
int x[3];
for(int i = 0; i < 3; i++)
{
    cin>>x[i];
}
sort(x,x+3);
int min=(x[2]-x[1])+(x[1]-x[0]);
cout<<min<<endl;

return 0;
}